#!/bin/bash
echo MTA Build Starting

#echo "Arg1 $1"
#echo "Arg2 $2"
#echo "Arg3 $3"
#echo "Arg4 $4"
#echo "Arg5 $5"

#java -jar "/Users/i830671/Documents/XSA/buildpacks/mta_python_dev_env/tools/mta.jar" $1 $2 $3 $4 $5 $6 $7 $8 $9
java -jar tools/mta.jar $1 $2 $3 $4 $5 $6 $7 $8 $9

echo MTA Build Finished

