#!/bin/bash
echo ""
xsorcf=$1
#Customize the org and space to your own situation
#org="HANAExpress"
org="LCFX"
#space="delvelopment"
space="DEV"
path=$2
proj="python-dev-env"
app=$proj"_"$path
host=$app"-"$path
dowait=""
doexport1=""
doexport2=""
if [ "$#" -eq 2 ]; then
  if [ $xsorcf = "xs" ]; then
    dowait=" --wait-indefinitely"
    doexport1=" --export-json /dev/stdout 2>/dev/null | tail -n +5"
    echo "XS cool."
  else
    if [ $xsorcf = "cf" ]; then
      doexport1=" | tail -n +5 | head -n -8"
      doexport2=" | head -n -1"
      echo "CF cool."
    else
      echo "Not XS or CF, try again."
      exit 1
    fi
  fi

  echo Client Python $xsorcf Deploy into org: $org space: $space Starting 
  echo ""

  cmd=$xsorcf' push '$app' -k 1024M -m 256M -p '$path' --no-start'
  echo $cmd
  eval $cmd

  uaa_instance=$proj"-uaa"
  hdi_instance=$proj"-hdi"

  cmd=$xsorcf' bind-service '$app' '$uaa_instance
  echo $cmd
  eval $cmd

  cmd=$xsorcf' bind-service '$app' '$hdi_instance
  echo $cmd
  eval $cmd

  cmd=$xsorcf' restart '$app' '$dowait
  echo $cmd
  eval $cmd

  echo ""

  cmd='HDI_SCHEMA=$('$xsorcf' env '$app' '$doexport1' | jq -r '"'"'.VCAP_SERVICES.hana[0].credentials.schema'"'"$doexport2')'
  #echo $cmd
  eval $cmd
  echo 'HDI_SCHEMA='$HDI_SCHEMA

  cmd='HDI_USER=$('$xsorcf' env '$app' '$doexport1' | jq -r '"'"'.VCAP_SERVICES.hana[0].credentials.user'"'"$doexport2')'
  #echo $cmd
  eval $cmd
  echo 'HDI_USER='$HDI_USER

  cmd='HDI_PASS=$('$xsorcf' env '$app' '$doexport1' | jq -r '"'"'.VCAP_SERVICES.hana[0].credentials.password'"'"$doexport2')'
  #echo $cmd
  eval $cmd
  echo 'HDI_PASS='$HDI_PASS

else
    echo "Usage ./py_deploy xs[cf] path"
    exit 1
fi
echo ""
echo Client HDI Deploy Finished
